hivepngs:
	inkscape -D --export-png=agency.png --export-dpi=100 agency.svg
	inkscape -D --export-png=Academia.png --export-dpi=100 Academia.svg
	inkscape -D --export-png=Gobierno.png --export-dpi=100 Gobierno.svg
	inkscape -D --export-png=Privado.png --export-dpi=100 Privado.svg
	inkscape -D --export-png=Sociedad_Civil.png --export-dpi=100 Sociedad_Civil.svg


hiveplots:
	python ../fobject/hiveplot.py all
	python ../fobject/hiveplot.py Academia
	python ../fobject/hiveplot.py Gobierno
	python ../fobject/hiveplot.py Privado
	python ../fobject/hiveplot.py Sociedad_Civil
